2018-09-04 18:16:47,342 ERROR: Exception on /reset_password_request [POST] [in c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\routes.py", line 182, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\email.py", line 28, in send_password_reset_email
    user=user, token=token))
  File "C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\email.py", line 17, in send_email
    mail.send(msg)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask_mail.py", line 192, in send
    message.rcpt_options)
  File "C:\Users\baobaobao123\Anaconda3\lib\smtplib.py", line 888, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (554, b'DT:SPM 163 smtp7,C8CowACXz7ePW45bTiEEPg--.24278S3 1536056208,please see http://mail.163.com/help/help_spam_16.htm?ip=61.136.151.254&hostid=smtp7&time=1536056208')
2018-09-04 18:24:10,985 INFO: Microblog startup [in C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\__init__.py:54]
2018-09-04 18:27:12,345 INFO: Microblog startup [in C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\__init__.py:54]
2018-09-04 18:27:48,264 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6OSwiZXhwIjoxNTM2MDU3NDM4LjI4OTc3Mn0.cP90vsd3fiIb9-JVNaGVtjaJ0-pnIAaMCeaW8ytxdC4 [GET] [in c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\routes.py", line 198, in reset_password
    user.set_password(form.password.data).first()
  File "C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\models.py", line 43, in set_password
    self.password_hash = generate_password_hash(password)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\werkzeug\security.py", line 230, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\werkzeug\security.py", line 192, in _hash_internal
    hashfunc=hash_func)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\werkzeug\security.py", line 64, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\werkzeug\security.py", line 104, in pbkdf2_bin
    keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2018-09-04 18:30:25,955 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6OSwiZXhwIjoxNTM2MDU3NDM4LjI4OTc3Mn0.cP90vsd3fiIb9-JVNaGVtjaJ0-pnIAaMCeaW8ytxdC4 [GET] [in c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\routes.py", line 198, in reset_password
    user.set_password(form.password.data)
  File "C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\models.py", line 43, in set_password
    self.password_hash = generate_password_hash(password)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\werkzeug\security.py", line 230, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\werkzeug\security.py", line 192, in _hash_internal
    hashfunc=hash_func)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\werkzeug\security.py", line 64, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "c:\users\baobaobao123\desktop\博客相关\flask\microblog\venv\lib\site-packages\werkzeug\security.py", line 104, in pbkdf2_bin
    keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2018-09-04 18:31:13,813 INFO: Microblog startup [in C:\Users\baobaobao123\Desktop\博客相关\flask\microblog\app\__init__.py:54]
